name: Publish Prerelease NuGets
on:
  push:
    branches:
      - prerelease
env:
  TIMESTAMP: $(date +'%s')
jobs:
  publish:
    name: Build and publish on windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x

      - name: Remove Samples
        run: dotnet sln Diagnostic.Extensions.sln remove (ls -r samples/**/*.csproj)

      - name: Restore NuGets
        run: dotnet restore Diagnostic.Extensions.sln

      - name: Build and Pack Solution
        run: dotnet pack Diagnostic.Extensions.sln --configuration Release --no-restore --version-suffix priview-${{ env.TIMESTAMP }}

      - name: Run Tests
        run: dotnet test --configuration Release --no-build Diagnostic.Extensions.sln

      - name: Publish
        run: dotnet nuget push nugets/*.nupkg -k ${{ secrets.API_KEY }} -s https://api.nuget.org/v3/index.json
